movieproject/movie/movie/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieA.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movie/movieA/urls.py
from django.urls import path
from .import views
app_name='movieA'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/movie/movieA/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name= models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

movieproject/movie/movieA/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movie/movieA/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request, movie_id):
    movie=Movie.objects.get(id=movie_id)

    return render(request,'detail.html',{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.POST.get('img', )
        movie=Movie.objects.get(name=name,desc=desc,year=year,img=img)
        movie.save()


    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/movie/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter the movie name">
    <input type="text" name="desc" placeholder="enter the movie description">
    <input type="int" name="year" placeholder="enter the movie year">
    <input type="file" name="img" >
    <input type="submit">
</form>
{% endblock %}

movieproject/movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">

   online movie
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/movie/templates/delete.html
<form method="post">
    {% csrf_token %}
    are you want to delete this movie
    <input type="submit">
</form>

movieproject/movie/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300"><br>

        </div>
<div class="col-md-6">
    <h6>{{movie.name}}</h6>
    <h6>{{movie.desc}}</h6>
    <h4>{{movie.year}}</h4>
    <a class="btn btn-warning" href="{% url 'movieA:update' movie.id  %}">update</a><br>
    <a class="btn btn-warning" href="{% url 'movieA:delete' movie.id  %}">delete</a><br>
</div>
    </div>
</div>





{% endblock %}

movieproject/movie/templates/edit.html
<form action="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/movie/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container"
     <div class="row">
         {% for i in movie_list %}
         <div class="col-md-3">
             <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="100px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{%url 'movieA:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

         </div>
         {% endfor %}


     </div>
</div




{% endblock %}